env:
  global:
    - CC_TEST_REPORTER_ID=579e877607570b4d0f1e7237aeea18480e0a744d74b9b1871d703a40ceddfec0

language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules
    - client/node_modules

script:
  - npm test
  
deploy:
  provider: heroku
  api_key:
    secure: 1917c827-5ade-44a4-8fa5-e872874e5c48
  app: array_of_sunshine
    on:
      repo: bibicollins/array_of_sunshine
      run: - "npm install"
           - "npm start"
